# YAML for the boys, cuz I'm bored of always using JSON.
model_server:
  stable_diffusion_server: localhost
  stable_diffusion_port: 5000
  stable_diffusion_uri: img_chat
  chat_server: localhost
  chat_port: 5000
  chat_uri: text_chat
Paths:
  data_path: {hydra:runtime.cwd}/data/
  log_path: ./logs
chat_gpt_fallback: True